server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  server:
    peerEurekaNodesUpdateIntervalMs: 30
  client:
    peerNodeReadTimeoutMs: 2
    serviceUrl:
      defaultZone: http://peer3:8763/eureka/
server:
  port: 8762

---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  server:
    peerEurekaNodesUpdateIntervalMs: 30
  client:
    peerNodeReadTimeoutMs: 2
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
      
server:
  port: 8763
